package me.steven.indrev.utils

import net.minecraft.util.Identifier

val hiddenIds = arrayOf(
    "heliostat",
    "resistant_glass",
    "solar_receiver",
    "fluid_valve",
    "molten_salt",
    "steam_turbine_mk4",
    "steam_turbine_steam_input_valve",
    "steam_turbine_energy_output",
    "steam_turbine_casing",
    "steam_turbine_rotor",
    "steam_turbine_pressure_valve",
    "solar_power_plant_tower",
    "solar_power_plant_smelter",
    "boiler",
    "steam",
    "carbon_fiber_plate",
    "carbon_fiber_rod",
    "salt",
    "carbon_fiber_helmet_frame",
    "carbon_fiber_chest_frame",
    "carbon_fiber_legs_frame",
    "carbon_fiber_boots_frame",
    "module_controlled_destruction",
    "module_matter_projector",
    "biomass_composter",
    "hydrogen_bucket",
    "oxygen_bucket",
    "methane_bucket",
    "steam_bucket",
    "molten_salt_bucket",
    "jetpack_mk1",
    "jetpack_mk2",
    "jetpack_mk3",
    "jetpack_mk4",
    "distiller_mk4",
    "module_magnet",
    "gas_generator_mk4",
    "dirt_oxygenator_mk1",
    "soot",
    "electrolytic_separator_mk1",
    "electrolytic_separator_mk2",
    "electrolytic_separator_mk3",
    "electrolytic_separator_mk4",
    "electrolytic_separator_creative",
    "module_water_affinity",
    "module_jetpack",
    "reinforced_elytra",
    "module_reinforced_elytra"
)

fun hide(id: Identifier) = id.namespace == "indrev" && hiddenIds.contains(id.path)