package me.steven.indrev.utils

enum class Upgrade() {
    AUTOMATED_ITEM_TRANSFER,
    AUTOMATED_FLUID_TRANSFER,
    OVERCLOCKER,
    OVERCLOCKER_2X,
    OVERCLOCKER_4X,
    OVERCLOCKER_8X,
    FUEL_EFFICIENCY;

    companion object {
        val CRAFTING = arrayOf(AUTOMATED_ITEM_TRANSFER, AUTOMATED_FLUID_TRANSFER, OVERCLOCKER, OVERCLOCKER_2X, OVERCLOCKER_4X, OVERCLOCKER_8X)
    }
}